import React from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function ReservationsScreen({ items, onBack, onSearch, onCancel }) {
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
    <Pressable onPress={onBack}><Text style={s.back}>‹ Back to home</Text></Pressable><Text style={s.title}>My reservations</Text><Text style={s.sub}>Manage your book pickups.</Text>
    {items.length ? <><Text style={s.heading}>Ready for pickup</Text>{items.map((book)=><View key={book.id} style={s.card}><View style={[s.cover,{backgroundColor:book.color}]}><Text style={s.initial}>{book.title[0]}</Text></View><View style={s.info}><Text style={s.bookTitle}>{book.title}</Text><Text style={s.author}>Pickup by tomorrow, 6:00 PM</Text><Text style={s.pickup}>Ready for pickup</Text><Pressable onPress={()=>onCancel(book)}><Text style={s.cancel}>Cancel reservation</Text></Pressable></View></View>)}<Pressable onPress={()=>items.forEach(onCancel)} style={s.secondary}><Text style={s.secondaryText}>Cancel all reservations</Text></Pressable></> : <View style={s.empty}><Text style={s.emptyIcon}>▣</Text><Text style={s.emptyTitle}>No reservations yet</Text><Text style={s.emptyCopy}>Search the catalogue and reserve an available book.</Text><Pressable onPress={onSearch} style={s.primary}><Text style={s.primaryText}>Search books</Text></Pressable></View>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FC'},page:{padding:20,paddingBottom:44},back:{color:'#304B9B',fontWeight:'800'},title:{fontSize:28,fontWeight:'900',color:'#1D2742',marginTop:24},sub:{color:'#69738D',marginTop:5},heading:{fontSize:19,fontWeight:'900',color:'#1D2742',marginTop:27,marginBottom:13},card:{flexDirection:'row',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E4E7F0',borderRadius:17,padding:13,marginBottom:12},cover:{width:62,height:84,borderRadius:10,alignItems:'center',justifyContent:'center'},initial:{fontSize:28,fontWeight:'900',color:'#243561'},info:{flex:1,marginLeft:13},bookTitle:{fontSize:16,fontWeight:'900',color:'#1D2742'},author:{color:'#69738D',marginTop:4},pickup:{color:'#168253',fontWeight:'900',marginTop:8},cancel:{color:'#B53C52',fontWeight:'900',marginTop:10},secondary:{borderWidth:1,borderColor:'#C9D0E2',backgroundColor:'#FFF',borderRadius:14,padding:16,alignItems:'center',marginTop:6},secondaryText:{color:'#304B9B',fontWeight:'900'},empty:{alignItems:'center',backgroundColor:'#FFF',borderRadius:18,padding:32,marginTop:28},emptyIcon:{fontSize:38,color:'#304B9B'},emptyTitle:{fontSize:19,fontWeight:'900',color:'#1D2742',marginTop:11},emptyCopy:{color:'#69738D',textAlign:'center',lineHeight:21,marginTop:7,marginBottom:17},primary:{backgroundColor:'#304B9B',borderRadius:14,padding:16,alignSelf:'stretch',alignItems:'center'},primaryText:{color:'#FFF',fontWeight:'900'} });
